"""OSMdwnl — декларативная загрузка OSM в GeoPackage."""
__version__ = "1.7.0"
SOFTWARE_NAME = "OSMdwnl"
ATTRIBUTION = "© OpenStreetMap contributors"
LICENSE = "ODbL 1.0 — https://www.openstreetmap.org/copyright"
